# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  push:
    branches: [ develop ]

env:
  S3_BUCKET_NAME: ticco-build

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create yml files
        working-directory: ./src/main/resources
        run: |
          touch application.yml
          touch application-jwt.yml
          touch application-aws.yml
          echo "${{ secrets.APPLICATION }}" >> application.yml
          echo "${{ secrets.APPLICATION_JWT }}" >> application-jwt.yml
          echo "${{ secrets.APPLICATION_AWS }}" >> application-aws.yml

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      #      - name: Test with Gradle
      #          run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash

      - name: Make zip file
        run: zip -r ./code-deploy.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY  }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./code-deploy.zip s3://$S3_BUCKET_NAME/code-deploy.zip

      - name: Code Deploy
        run: aws deploy create-deployment
          --application-name ticco-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name SERVER
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=code-deploy.zip
